# Generated by Django 5.2.6 on 2025-10-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=20, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('current_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('log_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mobile_list',
            },
        ),
        migrations.CreateModel(
            name='TransferGroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tran', models.IntegerField(default=0)),
                ('total_tran_amount', models.CharField(max_length=50)),
                ('success_tran_amount', models.CharField(max_length=50)),
                ('current_balance', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transfer_group_list',
            },
        ),
        migrations.CreateModel(
            name='TransferList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bene_acc_no', models.CharField(max_length=30)),
                ('bene_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('recRef', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='transfer.transfergrouplist')),
            ],
            options={
                'db_table': 'transfer_list',
            },
        ),
    ]
