# Generated by Django 5.2.6 on 2025-10-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferlist',
            name='group_id',
        ),
        migrations.AddField(
            model_name='transferlist',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='transfer.transfergrouplist'),
        ),
    ]
