# Generated by Django 5.2.6 on 2025-10-01 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
