# Generated by Django 5.2.6 on 2025-10-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfer', '0002_delete_logentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=20)),
                ('bene_acc_no', models.CharField(max_length=30)),
                ('bene_name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(max_length=20)),
                ('recRef', models.CharField(max_length=100)),
            ],
        ),
    ]
