# Generated by Django 5.2.6 on 2025-10-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_remove_transferlist_group_id_transferlist_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'transactions_status',
            },
        ),
        migrations.RenameModel(
            old_name='TransferGroupList',
            new_name='TransactionsGroupList',
        ),
        migrations.RenameModel(
            old_name='TransferList',
            new_name='TransactionsList',
        ),
        migrations.AlterModelTable(
            name='transactionsgrouplist',
            table='transactions_group_list',
        ),
        migrations.AlterModelTable(
            name='transactionslist',
            table='transactions_list',
        ),
    ]
