# Generated by Django 5.2.6 on 2025-10-01 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transferlist',
            table='transfer_list',
        ),
    ]
