# Generated by Django 5.2.6 on 2025-10-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_transactionsstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionsgrouplist',
            old_name='total_tran',
            new_name='total_tran_bene_amount',
        ),
    ]
