# Generated by Django 5.2.6 on 2025-10-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_rename_total_tran_transactionsgrouplist_total_tran_bene_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionsgrouplist',
            old_name='total_tran_bene_amount',
            new_name='total_tran_bene_acc',
        ),
    ]
