# Generated by Django 5.2.6 on 2025-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_transferlist_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlist',
            name='group_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
