# Generated by Django 5.2.6 on 2025-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_rename_total_tran_bene_amount_transactionsgrouplist_total_tran_bene_acc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_data', models.JSONField()),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('assigned_device', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pending_order',
            },
        ),
    ]
