# Generated by Django 5.2.6 on 2025-10-02 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_transferlist_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferlist',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
    ]
