# Generated by Django 5.2.6 on 2025-10-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_pendingorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingOrder',
        ),
        migrations.AlterField(
            model_name='transactionslist',
            name='status',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
