# Generated by Django 5.2.6 on 2025-10-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_transferlist_created_at_alter_transferlist_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlist',
            name='tran_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
