# Generated by Django 5.2.6 on 2025-10-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_alter_transferlist_tran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlist',
            name='group_id',
            field=models.IntegerField(),
        ),
    ]
