# Generated by Django 5.2.6 on 2025-10-09 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_delete_pendingorder_alter_transactionslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionslist',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.transactionsstatus'),
        ),
    ]
