# Generated by Django 5.2.6 on 2025-10-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_transferlist_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlist',
            name='group_id',
            field=models.CharField(max_length=50),
        ),
    ]
