# Generated by Django 5.2.6 on 2025-10-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_transactionslist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionslist',
            name='status',
            field=models.IntegerField(db_column='status_id', default=0),
        ),
    ]
