"""Add callback_status to TransactionsList

This migration was generated by the helper to add an integer field to track
whether a callback was successfully pushed for a transaction.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_alter_transactionslist_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionslist',
            name='callback_status',
            field=models.IntegerField(db_column='callback_status', default=0),
        ),
    ]
