# Generated by Django 5.2.6 on 2025-10-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0009_alter_transferlist_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlist',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
