# Generated by Django 5.2.6 on 2025-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_transferlist_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlist',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
