# Generated by Django 5.2.6 on 2025-10-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_alter_transferlist_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('current_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('user_id', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('tran_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('log_file', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mobile_list',
            },
        ),
    ]
