# Generated by Django 5.2.6 on 2025-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_mobilelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferGroupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_tran_id', models.CharField(max_length=50)),
                ('total_tran_amount', models.CharField(max_length=50)),
                ('success_tran_amount', models.CharField(max_length=50)),
                ('current_balance', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'transfer_group_list',
            },
        ),
    ]
