# Generated by Django 5.2.6 on 2025-10-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_transfergrouplist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilelist',
            old_name='phone_number',
            new_name='device',
        ),
    ]
