# Generated by Django 5.2.6 on 2025-10-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0014_rename_phone_number_mobilelist_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlist',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
