# Generated by Django 5.2.6 on 2025-10-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0015_transferlist_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlist',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transferlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
